### ISSUE TITLE
how can i contribute?

### ISSUE THREAD

**Issue by jacksolutions** [ivanalbizu/ionic#1]
How can i contribute on it? is there any module done besides listing of customers, invoices etc etc?

**Comment by jacksolutions** [comment]
is it possible to contribute on it?

**Comment by jacksolutions** [comment]
thank you for adding me to contribution, so let me know how to proceed now.. what features need to develop and roadmap?

**Comment by ivanalbizu** [comment]
I'm doing this project to learn to use ionic. I'm using the installation Odoo to see information from the database and make requests to paint in Ionic.
If you think of something you want to tell me

**Comment by jacksolutions** [comment]
i have sent you an email with possible next set of tasks, you can check in email.
